export const AUTHOR = Object.freeze({ name: "Pamas", role: "Author" });

export const categories = [
  { id: "nav", name: "Navigation", icon: "🧭", color: "#00d4ff" },
  { id: "files", name: "File Operations", icon: "📁", color: "#22c55e" },
  { id: "perm", name: "Permissions", icon: "🔒", color: "#fbbf24" },
  { id: "proc", name: "Processes", icon: "⚙️", color: "#ef4444" },
  { id: "net", name: "Networking", icon: "🌐", color: "#a78bfa" },
  { id: "txt", name: "Text Processing", icon: "📝", color: "#fb923c" },
  { id: "sys", name: "System Admin", icon: "🛠", color: "#38bdf8" },
  { id: "scripting", name: "Shell Scripting", icon: "📜", color: "#f472b6" },
];

export const commands = [
  { id: "ls", cat: "nav", name: "ls", level: "beginner", desc: "List directory contents with options for detailed view, hidden files, and sorting.", syntax: "ls -la", tags: ["list", "directory", "files"], detail: { full: "The ls command lists directory contents. It is one of the most used commands in Linux.", examples: [{ cmd: "ls", comment: "Basic listing" }, { cmd: "ls -l", comment: "Long format with permissions, size, date" }, { cmd: "ls -la", comment: "Include hidden files (dotfiles)" }, { cmd: "ls -lh", comment: "Human-readable file sizes" }, { cmd: "ls -lt", comment: "Sort by modification time" }, { cmd: "ls -R", comment: "Recursive listing of subdirectories" }], tip: "Use ls --color=auto or alias it in your .bashrc for colorized output." } },
  { id: "cd", cat: "nav", name: "cd", level: "beginner", desc: "Change the current working directory. Use ~ for home, .. for parent, - for previous.", syntax: "cd /path/to/dir", tags: ["navigate", "directory"], detail: { full: 'cd stands for "change directory". It is a shell built-in command for navigating the filesystem.', examples: [{ cmd: "cd ~", comment: "Go to home directory" }, { cmd: "cd ..", comment: "Go up one level" }, { cmd: "cd -", comment: "Go to previous directory" }, { cmd: "cd /var/log", comment: "Absolute path navigation" }, { cmd: "cd documents/projects", comment: "Relative path navigation" }], tip: "Press Tab to autocomplete directory names!" } },
  { id: "pwd", cat: "nav", name: "pwd", level: "beginner", desc: "Print Working Directory — shows the full absolute path of your current location.", syntax: "pwd", tags: ["path", "directory"], detail: { full: "pwd prints the full path of the current working directory.", examples: [{ cmd: "pwd", comment: "Show current location" }, { cmd: "pwd -P", comment: "Show physical path (resolve symlinks)" }], tip: "Use $PWD environment variable to get current directory in scripts." } },
  { id: "find", cat: "nav", name: "find", level: "intermediate", desc: "Search for files and directories based on name, type, size, permissions, and more.", syntax: 'find / -name "*.conf"', tags: ["search", "files", "locate"], detail: { full: "find is a powerful command for searching the filesystem with many filter options.", examples: [{ cmd: 'find . -name "*.log"', comment: "Find all .log files in current dir" }, { cmd: "find /var -type f -size +10M", comment: "Files larger than 10MB" }, { cmd: "find . -mtime -7", comment: "Modified in last 7 days" }, { cmd: "find / -perm 777", comment: "Files with 777 permissions" }, { cmd: 'find . -name "*.py" -exec grep -l "import os" {} \\;', comment: "Find python files containing text" }], tip: "Use -exec to run commands on found files. Use -maxdepth to limit search depth." } },
  { id: "cp", cat: "files", name: "cp", level: "beginner", desc: "Copy files or directories. Use -r for recursive directory copy, -p to preserve attributes.", syntax: "cp -r src/ dest/", tags: ["copy", "files"], detail: { full: "cp copies files and directories from source to destination.", examples: [{ cmd: "cp file.txt backup.txt", comment: "Simple file copy" }, { cmd: "cp -r /src /dest", comment: "Recursive directory copy" }, { cmd: "cp -p file.txt backup/", comment: "Preserve timestamps and permissions" }, { cmd: "cp -u *.txt backup/", comment: "Only copy if newer" }, { cmd: "cp -v file.txt dest/", comment: "Verbose output" }], tip: "Use rsync for large transfers — it is faster and supports incremental sync." } },
  { id: "mv", cat: "files", name: "mv", level: "beginner", desc: "Move or rename files and directories. The same command handles both operations.", syntax: "mv old.txt new.txt", tags: ["move", "rename"], detail: { full: "mv moves files from one location to another, or renames them if destination is in same directory.", examples: [{ cmd: "mv file.txt /tmp/", comment: "Move file to /tmp" }, { cmd: "mv old.txt new.txt", comment: "Rename file" }, { cmd: "mv -i file.txt dest/", comment: "Prompt before overwrite" }, { cmd: "mv -n file.txt dest/", comment: "Never overwrite existing" }], tip: "mv is instant for same-filesystem moves (no actual copy), but slow across filesystems." } },
  { id: "rm", cat: "files", name: "rm", level: "beginner", desc: "Remove files and directories. Be careful — there is no recycle bin in Linux!", syntax: "rm -rf directory/", tags: ["delete", "remove"], detail: { full: "rm removes files. The -r flag removes directories recursively. -f forces removal without prompts.", examples: [{ cmd: "rm file.txt", comment: "Remove a file" }, { cmd: "rm -r folder/", comment: "Remove directory recursively" }, { cmd: "rm -rf /tmp/cache/", comment: "Force remove (no prompts)" }, { cmd: "rm -i *.log", comment: "Prompt before each deletion" }], tip: "Never run rm -rf / or rm -rf * in root directory. There is no undo. Consider using trash-cli instead." } },
  { id: "tar", cat: "files", name: "tar", level: "intermediate", desc: "Archive and compress files. Essential for backups and transferring directories.", syntax: "tar -czf archive.tar.gz dir/", tags: ["archive", "compress", "backup"], detail: { full: "tar creates and extracts archives. Combined with gzip or bzip2 for compression.", examples: [{ cmd: "tar -czf backup.tar.gz /home/user", comment: "Create compressed archive" }, { cmd: "tar -xzf backup.tar.gz", comment: "Extract archive" }, { cmd: "tar -tzf archive.tar.gz", comment: "List archive contents" }, { cmd: "tar -xzf archive.tar.gz -C /tmp", comment: "Extract to specific dir" }, { cmd: "tar -cjf backup.tar.bz2 dir/", comment: "Use bzip2 (better compression)" }], tip: "Remember: -c create, -x extract, -t list, -z gzip, -j bzip2, -v verbose, -f filename" } },
  { id: "ln", cat: "files", name: "ln", level: "intermediate", desc: "Create hard and symbolic links. Symlinks are like shortcuts; hardlinks share the same inode.", syntax: "ln -s /original /link", tags: ["symlink", "hardlink"], detail: { full: "ln creates links between files. Symbolic links point to the path; hard links point to the inode.", examples: [{ cmd: "ln -s /usr/bin/python3 python", comment: "Create symlink" }, { cmd: "ln file.txt hardlink.txt", comment: "Create hard link" }, { cmd: 'ls -la | grep "^l"', comment: "List only symlinks" }, { cmd: "readlink -f symlink", comment: "Show real path of symlink" }], tip: "Use symbolic links for flexibility. Hard links cannot span filesystems or link to directories." } },
  { id: "chmod", cat: "perm", name: "chmod", level: "intermediate", desc: "Change file permissions using octal (755) or symbolic (u+x) notation.", syntax: "chmod 755 script.sh", tags: ["permissions", "security"], detail: { full: "chmod modifies the permission bits of files. Permissions: r=4, w=2, x=1.", examples: [{ cmd: "chmod 755 script.sh", comment: "rwxr-xr-x (owner full, others read+exec)" }, { cmd: "chmod 644 file.txt", comment: "rw-r--r-- (standard file permissions)" }, { cmd: "chmod +x run.sh", comment: "Add execute permission" }, { cmd: "chmod -R 755 directory/", comment: "Recursive permission change" }, { cmd: "chmod u+rw,g+r,o-rwx file", comment: "Symbolic notation" }], tip: "Common patterns: 755 for directories/executables, 644 for regular files, 600 for private keys, 777 should be avoided in production." } },
  { id: "chown", cat: "perm", name: "chown", level: "intermediate", desc: "Change file owner and group. Requires sudo for changing ownership to other users.", syntax: "chown user:group file", tags: ["owner", "permissions"], detail: { full: "chown changes the user and/or group ownership of files.", examples: [{ cmd: "chown paul:paul file.txt", comment: "Change owner and group" }, { cmd: "chown -R www-data /var/www", comment: "Recursive ownership change" }, { cmd: "chown :developers project/", comment: "Change only group" }, { cmd: "stat file.txt", comment: "View current ownership info" }], tip: "Use chown when moving files between users, or when web servers need to read files." } },
  { id: "sudo", cat: "perm", name: "sudo", level: "beginner", desc: "Execute commands as superuser (root). Configure with visudo. Never abuse root access!", syntax: "sudo command", tags: ["root", "admin", "superuser"], detail: { full: "sudo lets authorized users run commands as root or another user, configured in /etc/sudoers.", examples: [{ cmd: "sudo apt update", comment: "Run apt as root" }, { cmd: "sudo -i", comment: "Switch to root shell (interactive)" }, { cmd: "sudo -u postgres psql", comment: "Run as different user" }, { cmd: "sudo visudo", comment: "Safely edit sudoers file" }, { cmd: "sudo !!", comment: "Re-run last command with sudo" }], tip: "sudo !! is a huge timesaver. Also check /var/log/auth.log for sudo usage history." } },
  { id: "ps", cat: "proc", name: "ps", level: "beginner", desc: "Display information about running processes. Use aux for all processes with details.", syntax: "ps aux", tags: ["process", "monitor"], detail: { full: "ps shows a snapshot of currently running processes with details about CPU and memory usage.", examples: [{ cmd: "ps aux", comment: "All processes with user, CPU, mem" }, { cmd: "ps aux | grep nginx", comment: "Find specific process" }, { cmd: "ps -ef --forest", comment: "Show process tree" }, { cmd: "ps -o pid,ppid,cmd,%mem,%cpu", comment: "Custom output columns" }], tip: "Use top or htop for real-time monitoring. pgrep nginx is cleaner than ps aux | grep nginx." } },
  { id: "kill", cat: "proc", name: "kill / killall", level: "intermediate", desc: "Send signals to processes to terminate or control them. SIGTERM (15) is graceful, SIGKILL (9) is force.", syntax: "kill -9 PID", tags: ["process", "terminate", "signal"], detail: { full: "kill sends signals to processes. SIGTERM requests graceful shutdown; SIGKILL forces immediate termination.", examples: [{ cmd: "kill 1234", comment: "Graceful terminate by PID" }, { cmd: "kill -9 1234", comment: "Force kill (cannot be caught)" }, { cmd: "killall nginx", comment: "Kill all nginx processes" }, { cmd: 'pkill -f "python script.py"', comment: "Kill by command name pattern" }, { cmd: "kill -l", comment: "List all signal names" }], tip: "Always try SIGTERM first. SIGKILL can leave temp files and corrupt data. Use kill -HUP to reload configs." } },
  { id: "top", cat: "proc", name: "top / htop", level: "beginner", desc: "Real-time system monitor showing processes, CPU, memory. htop is the enhanced interactive version.", syntax: "htop", tags: ["monitor", "cpu", "memory"], detail: { full: "top provides real-time view of running processes. htop adds color, mouse support, and easier navigation.", examples: [{ cmd: "top", comment: "Basic real-time monitor" }, { cmd: "htop", comment: "Enhanced interactive monitor" }, { cmd: "top -u username", comment: "Show only user processes" }, { cmd: "top -p 1234,5678", comment: "Monitor specific PIDs" }], tip: "In htop: F3 to search, F9 to kill, F6 to sort, Space to tag multiple processes. Install with: sudo apt install htop" } },
  { id: "systemctl", cat: "proc", name: "systemctl", level: "intermediate", desc: "Control systemd services: start, stop, restart, enable, disable, and check status of services.", syntax: "systemctl status nginx", tags: ["service", "systemd", "daemon"], detail: { full: "systemctl is the primary tool for managing systemd services on modern Linux distributions.", examples: [{ cmd: "systemctl status nginx", comment: "Check service status" }, { cmd: "systemctl start nginx", comment: "Start a service" }, { cmd: "systemctl stop nginx", comment: "Stop a service" }, { cmd: "systemctl restart nginx", comment: "Restart service" }, { cmd: "systemctl enable nginx", comment: "Start on boot" }, { cmd: "systemctl disable nginx", comment: "Don't start on boot" }, { cmd: "journalctl -u nginx -f", comment: "Follow service logs" }], tip: "Use journalctl -xe to see detailed error logs when a service fails to start." } },
  { id: "curl", cat: "net", name: "curl", level: "intermediate", desc: "Transfer data from URLs. Perfect for API testing, downloading files, and HTTP debugging.", syntax: "curl -I https://example.com", tags: ["http", "api", "download"], detail: { full: "curl is a versatile tool for transferring data using various protocols including HTTP, FTP, SMTP.", examples: [{ cmd: "curl https://api.example.com/users", comment: "GET request" }, { cmd: 'curl -X POST -d "data" url', comment: "POST request" }, { cmd: 'curl -H "Auth: token" url', comment: "Custom header" }, { cmd: "curl -o file.zip url", comment: "Download to file" }, { cmd: "curl -I url", comment: "Show only headers" }, { cmd: "curl -s url | jq .", comment: "Pretty-print JSON response" }], tip: "Use -v for verbose mode to debug request/response headers. -s for silent (no progress bar)." } },
  { id: "ssh", cat: "net", name: "ssh", level: "intermediate", desc: "Secure Shell for remote login and remote command execution over encrypted connections.", syntax: "ssh user@host -p 22", tags: ["remote", "secure", "login"], detail: { full: "SSH (Secure Shell) provides encrypted remote access to Linux systems.", examples: [{ cmd: "ssh user@192.168.1.10", comment: "Basic SSH connection" }, { cmd: "ssh -i ~/.ssh/key.pem user@host", comment: "Use specific private key" }, { cmd: "ssh -p 2222 user@host", comment: "Non-standard port" }, { cmd: "ssh -L 8080:localhost:80 user@host", comment: "Local port forwarding (tunnel)" }, { cmd: "ssh-keygen -t ed25519", comment: "Generate modern SSH keypair" }, { cmd: "ssh-copy-id user@host", comment: "Copy public key to server" }], tip: "Use SSH config file (~/.ssh/config) to save connection shortcuts. Ed25519 keys are more secure than RSA-2048." } },
  { id: "netstat", cat: "net", name: "ss / netstat", level: "advanced", desc: "Display network connections, routing tables, interface stats, and port usage.", syntax: "ss -tulpn", tags: ["ports", "network", "sockets"], detail: { full: "ss (socket statistics) replaces netstat. Shows active connections, listening ports, and socket info.", examples: [{ cmd: "ss -tulpn", comment: "Show all listening ports with process names" }, { cmd: "ss -s", comment: "Socket summary statistics" }, { cmd: "ss -tp", comment: "TCP connections with process info" }, { cmd: "netstat -rn", comment: "Show routing table" }, { cmd: "lsof -i :80", comment: "What process is using port 80" }], tip: "ss is faster than netstat as it directly reads kernel data. -t TCP, -u UDP, -l listening, -p process, -n numeric." } },
  { id: "iptables", cat: "net", name: "iptables / nftables", level: "pro", desc: "Packet filtering firewall for managing network traffic rules, NAT, and port forwarding.", syntax: "iptables -L -n -v", tags: ["firewall", "security", "network"], detail: { full: "iptables controls the Linux kernel's netfilter framework. nftables is the modern replacement.", examples: [{ cmd: "iptables -L -n -v", comment: "List all rules with stats" }, { cmd: "iptables -A INPUT -p tcp --dport 80 -j ACCEPT", comment: "Allow HTTP" }, { cmd: "iptables -A INPUT -s 192.168.1.0/24 -j DROP", comment: "Block subnet" }, { cmd: "iptables-save > rules.v4", comment: "Save rules" }, { cmd: "ufw allow 22/tcp", comment: "UFW: allow SSH (easier interface)" }, { cmd: "ufw status verbose", comment: "UFW: show current rules" }], tip: "For most use cases, use ufw (Uncomplicated Firewall) or firewalld instead of raw iptables." } },
  { id: "grep", cat: "txt", name: "grep", level: "beginner", desc: "Search for patterns in files using regular expressions. One of the most powerful Linux tools.", syntax: 'grep -rn "pattern" ./', tags: ["search", "regex", "text"], detail: { full: "grep searches file contents for lines matching a pattern. Supports basic and extended regex.", examples: [{ cmd: 'grep "error" /var/log/syslog', comment: "Search in file" }, { cmd: 'grep -rn "TODO" ./src', comment: "Recursive search with line numbers" }, { cmd: 'grep -i "ERROR" log.txt', comment: "Case-insensitive search" }, { cmd: 'grep -v "DEBUG" app.log', comment: "Invert match (exclude lines)" }, { cmd: 'grep -c "error" log.txt', comment: "Count matching lines" }, { cmd: 'grep -A 3 -B 1 "FATAL" log', comment: "Show context lines" }], tip: "Use egrep (grep -E) for extended regex. Use grep -P for Perl-compatible regex (lookaheads, etc)." } },
  { id: "awk", cat: "txt", name: "awk", level: "advanced", desc: "Powerful text processing language for field-based data manipulation, reports, and transformations.", syntax: "awk '{print $1, $3}' file", tags: ["text", "fields", "parsing"], detail: { full: "awk is a complete programming language for text processing, treating input as records with fields.", examples: [{ cmd: "awk '{print $1}' file.txt", comment: "Print first field (space-delimited)" }, { cmd: "awk -F: '{print $1}' /etc/passwd", comment: "Use : as delimiter (usernames)" }, { cmd: "awk '{sum+=$3} END{print sum}' data", comment: "Sum column 3" }, { cmd: "awk 'NR>5 && NR<10' file", comment: "Print lines 6-9" }, { cmd: "awk '$3>100 {print $0}' data", comment: "Conditional printing" }, { cmd: "ps aux | awk '{print $1,$11}' | sort | uniq", comment: "Process owner list" }], tip: "BEGIN and END blocks run before/after processing. NR=record number, NF=number of fields. Extremely powerful for log analysis." } },
  { id: "sed", cat: "txt", name: "sed", level: "advanced", desc: "Stream editor for filtering and transforming text. Great for in-place file edits and substitutions.", syntax: "sed -i 's/old/new/g' file", tags: ["replace", "edit", "stream"], detail: { full: "sed (stream editor) processes text line-by-line, applying transformations.", examples: [{ cmd: "sed 's/foo/bar/' file.txt", comment: "Replace first occurrence per line" }, { cmd: "sed 's/foo/bar/g' file.txt", comment: "Replace all occurrences" }, { cmd: "sed -i 's/old/new/g' file.txt", comment: "Edit file in-place" }, { cmd: "sed -n '5,10p' file.txt", comment: "Print lines 5-10" }, { cmd: "sed '/^#/d' config.txt", comment: "Delete comment lines" }, { cmd: "sed -i.bak 's/http/https/g' *.conf", comment: "In-place with backup" }], tip: "Always make a backup before -i (in-place) edits. Use -i.bak to auto-create backups. Test without -i first." } },
  { id: "pipe", cat: "txt", name: "Pipes & Redirection", level: "beginner", desc: "Chain commands with | (pipe), redirect output with >, append with >>, and input with <.", syntax: "cmd1 | cmd2 | cmd3", tags: ["pipe", "redirect", "stdin", "stdout"], detail: { full: "Unix pipes allow output of one command to become input of another, enabling powerful command chaining.", examples: [{ cmd: "ls -la | sort -k5 -n", comment: "List files sorted by size" }, { cmd: "ps aux | grep nginx | awk '{print $2}'", comment: "Get nginx PIDs" }, { cmd: "cat /etc/passwd | cut -d: -f1 | sort", comment: "Sorted usernames" }, { cmd: 'echo "text" > file.txt', comment: "Redirect to file (overwrite)" }, { cmd: 'echo "more" >> file.txt', comment: "Append to file" }, { cmd: "command 2>&1 | tee output.log", comment: "Log stdout and stderr" }], tip: "tee is useful to see output AND save to file. Use 2>/dev/null to suppress errors. | xargs converts stdin to arguments." } },
  { id: "df", cat: "sys", name: "df / du", level: "beginner", desc: "Check disk space usage. df shows filesystem usage; du shows directory/file sizes.", syntax: "df -h && du -sh *", tags: ["disk", "storage", "space"], detail: { full: "df reports disk space usage for filesystems; du estimates file space usage.", examples: [{ cmd: "df -h", comment: "Human-readable disk usage" }, { cmd: "df -h /home", comment: "Check specific partition" }, { cmd: "du -sh /var/log", comment: "Total size of directory" }, { cmd: "du -sh * | sort -h", comment: "Sort by size" }, { cmd: "du -h --max-depth=1 /", comment: "Top-level directory sizes" }, { cmd: "ncdu /", comment: "Interactive disk usage browser (install separately)" }], tip: "ncdu is an excellent interactive tool for finding what is eating your disk space." } },
  { id: "cron", cat: "sys", name: "cron / crontab", level: "intermediate", desc: "Schedule tasks to run automatically at specific times, dates, or intervals.", syntax: "crontab -e", tags: ["schedule", "automation", "cron"], detail: { full: "cron is the Linux task scheduler. crontab manages individual user cron jobs.", examples: [{ cmd: "crontab -e", comment: "Edit current user cron jobs" }, { cmd: "crontab -l", comment: "List current cron jobs" }, { cmd: "sudo crontab -e -u www-data", comment: "Edit cron for other user" }, { cmd: "cat /etc/crontab", comment: "System-wide crontab" }], tip: 'Cron syntax: MIN HOUR DAY MON DOW CMD. Use "30 2 * * 0" for every Sunday at 2:30am. Test with: crontab -l | crontab -' } },
  { id: "env", cat: "sys", name: "env / export", level: "intermediate", desc: "Manage environment variables. export makes variables available to child processes.", syntax: "export VAR=value", tags: ["environment", "variables", "config"], detail: { full: "Environment variables store configuration values accessible to processes and their children.", examples: [{ cmd: "env", comment: "Show all environment variables" }, { cmd: "echo $PATH", comment: "Show specific variable" }, { cmd: 'export API_KEY="secret"', comment: "Set and export variable" }, { cmd: "export PATH=$PATH:/new/bin", comment: "Add to PATH" }, { cmd: "unset VARIABLE", comment: "Remove variable" }, { cmd: "printenv HOME SHELL", comment: "Print specific vars" }], tip: "Add exports to ~/.bashrc or ~/.bash_profile for persistence. Use .env files in projects with source .env." } },
  { id: "strace", cat: "sys", name: "strace / ltrace", level: "pro", desc: "Trace system calls and signals made by a process. Invaluable for debugging mysterious failures.", syntax: "strace -p PID", tags: ["debug", "syscall", "trace"], detail: { full: "strace traces system calls made by a process, helping debug permission errors, missing files, and crashes.", examples: [{ cmd: "strace ls /tmp", comment: "Trace all syscalls of ls" }, { cmd: "strace -p 1234", comment: "Attach to running process" }, { cmd: "strace -e trace=file ls", comment: "Only trace file-related calls" }, { cmd: "strace -o trace.log command", comment: "Save output to file" }, { cmd: "strace -c command", comment: "Count syscalls (summary)" }], tip: "strace output is verbose. Filter with -e. Look for ENOENT (file not found) and EACCES (permission denied) errors." } },
  { id: "bash-basics", cat: "scripting", name: "Bash Basics", level: "intermediate", desc: "Write shell scripts with variables, conditionals, loops, and functions to automate tasks.", syntax: "#!/bin/bash", tags: ["bash", "script", "automation"], detail: { full: "Bash scripting automates repetitive tasks, combining commands with logic and control flow.", examples: [{ cmd: "#!/bin/bash", comment: "Shebang line — always first" }, { cmd: 'VAR="hello"', comment: "Variable assignment (no spaces!)" }, { cmd: 'echo "Value: $VAR"', comment: "Variable expansion" }, { cmd: 'if [ -f "$FILE" ]; then echo "exists"; fi', comment: "File existence check" }, { cmd: "for i in {1..5}; do echo $i; done", comment: "For loop" }, { cmd: 'while read line; do echo "$line"; done < file', comment: "Read file line by line" }], tip: 'Always quote variables "$VAR" to prevent word splitting. Use shellcheck to lint your scripts.' } },
  { id: "bash-adv", cat: "scripting", name: "Advanced Bash", level: "advanced", desc: "Functions, arrays, associative arrays, process substitution, and error handling in bash.", syntax: "set -euo pipefail", tags: ["bash", "functions", "arrays"], detail: { full: "Advanced bash features enable robust, maintainable scripts with proper error handling.", examples: [{ cmd: "set -euo pipefail", comment: "Exit on error, undefined var, pipe fail" }, { cmd: 'function greet() { echo "Hello $1"; }', comment: "Function definition" }, { cmd: 'arr=("a" "b" "c")', comment: "Array declaration" }, { cmd: 'echo "${arr[@]}"', comment: "Expand all array elements" }, { cmd: "declare -A map; map[key]=value", comment: "Associative array" }, { cmd: "result=$(command)", comment: "Command substitution" }], tip: 'Always start production scripts with set -euo pipefail. Use trap for cleanup on exit: trap "rm -f $TMPFILE" EXIT' } },
  { id: "regex", cat: "scripting", name: "Regular Expressions", level: "advanced", desc: "Pattern matching with regex: anchors, character classes, quantifiers, groups, and lookaheads.", syntax: "/^[A-Z][a-z]+$/", tags: ["regex", "pattern", "match"], detail: { full: "Regular expressions are patterns for matching and manipulating text in grep, sed, awk, and programming languages.", examples: [{ cmd: "grep -E '^[0-9]+$' file", comment: "Match lines with only digits" }, { cmd: "grep -E '^\\s*#' file", comment: "Match comment lines" }, { cmd: "grep -oP '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}' log", comment: "Extract IP addresses" }, { cmd: "sed -E 's/([0-9]{4})-([0-9]{2})/\\2-\\1/' file", comment: "Swap date format" }, { cmd: "awk '/ERROR|FATAL/{print}'", comment: "Match multiple patterns" }], tip: "Anchors: ^ start, $ end. Quantifiers: * zero+, + one+, ? optional, {n,m} range. Groups: () capture, (?:) non-capture." } },
];

export const roadmap = [
  { num: "01", title: "Shell Basics", status: "done", desc: "Navigate the filesystem, understand the terminal, learn fundamental commands.", topics: ["pwd, ls, cd", "cp, mv, rm", "cat, less, more", "man pages", "Tab completion"] },
  { num: "02", title: "File System & Permissions", status: "done", desc: "Understand the Linux filesystem hierarchy and file permission model.", topics: ["FHS structure", "/etc /var /home /proc", "/usr /bin /sbin", "chmod, chown", "File types"] },
  { num: "03", title: "Text Processing", status: "active", desc: "Master the power of text manipulation tools - the heart of Linux.", topics: ["grep & regex", "sed stream editor", "awk language", "cut, sort, uniq", "wc, head, tail", "Pipes & redirection"] },
  { num: "04", title: "User & Group Management", status: "locked", desc: "Manage users, groups, and access control effectively.", topics: ["useradd, usermod", "/etc/passwd", "Groups & sudoers", "PAM authentication", "ACLs"] },
  { num: "05", title: "Process Management", status: "locked", desc: "Understand how Linux manages processes, jobs, and resources.", topics: ["Process lifecycle", "ps, top, htop", "kill, signals", "Jobs & background", "nice, renice", "/proc filesystem"] },
  { num: "06", title: "Networking Fundamentals", status: "locked", desc: "TCP/IP, network configuration, and connectivity tools.", topics: ["ip, ifconfig", "ping, traceroute", "DNS & /etc/hosts", "curl, wget", "ss, netstat", "SSH mastery"] },
  { num: "07", title: "Shell Scripting", status: "locked", desc: "Write powerful automation scripts with bash.", topics: ["Variables & quoting", "Conditionals", "Loops & functions", "Arrays", "Error handling", "Cron scheduling"] },
  { num: "08", title: "System Administration", status: "locked", desc: "Service management, logging, performance, and maintenance.", topics: ["systemd & services", "journalctl", "Disk & LVM", "Package management", "Log rotation", "Performance tuning"] },
  { num: "09", title: "Security Hardening", status: "locked", desc: "Secure your Linux systems against threats.", topics: ["iptables / ufw", "SSH hardening", "File integrity", "SELinux / AppArmor", "Audit logs", "Fail2ban"] },
  { num: "10", title: "Advanced & Pro Topics", status: "locked", desc: "Kernel tuning, containers, and production-grade skills.", topics: ["Kernel parameters", "systemctl deep dive", "LXC / Docker", "Ansible basics", "strace / perf", "Custom kernels"] },
];

export const quizQuestions = [
  { question: "What command shows all running processes with CPU and memory usage?", options: ["ls -la", "ps aux", "cat /proc", "jobs -l"], answer: 1, explain: "ps aux shows all processes for all users with detailed CPU and memory info." },
  { question: "Which flag makes chmod apply changes recursively to all files in a directory?", options: ["-a", "-f", "-R", "-v"], answer: 2, explain: "-R applies chmod recursively to all files and subdirectories." },
  { question: "What does the pipe operator | do?", options: ["Redirect output to a file", "Send output of one command as input to another", "Run two commands simultaneously", "Append to a file"], answer: 1, explain: "The pipe | takes stdout of the left command and passes it as stdin to the right command." },
  { question: "Which command shows your current directory path?", options: ["cd", "ls -d", "pwd", "whereis ."], answer: 2, explain: "pwd (Print Working Directory) shows the full absolute path of where you are." },
  { question: "What does chmod 755 mean in octal notation?", options: ["rwxrwxrwx", "rwxr-xr-x", "rw-rw-rw-", "rwx------"], answer: 1, explain: "7=rwx, 5=r-x, 5=r-x. Owner has full access, group and others can read and execute." },
  { question: 'Which command would you use to find all .log files in /var recursively?', options: ["ls -r /var *.log", 'find /var -name "*.log"', 'grep -r ".log" /var', "locate /var/*.log"], answer: 1, explain: 'find /var -name "*.log" recursively searches /var for files matching the pattern.' },
  { question: "What does grep -v do?", options: ["Search in verbose mode", "Show version", "Invert match (exclude matching lines)", "Recursive grep"], answer: 2, explain: "-v inverts the match, showing lines that do NOT match the pattern." },
  { question: "Which systemctl command makes a service start automatically on boot?", options: ["systemctl start nginx", "systemctl enable nginx", "systemctl activate nginx", "systemctl autostart nginx"], answer: 1, explain: "systemctl enable creates a symlink so the service starts on next boot." },
  { question: "What does set -e do at the start of a bash script?", options: ["Enable extended globbing", "Exit immediately if any command fails", "Enable debug mode", "Set environment variables"], answer: 1, explain: "set -e causes the script to exit immediately when any command returns a non-zero exit code." },
  { question: "What is the purpose of the >> operator?", options: ["Redirect and overwrite file", "Compare two files", "Append output to a file", "Pipe to a command"], answer: 2, explain: ">> appends stdout to the end of a file, preserving existing content. > overwrites." },
  { question: "Which signal does kill -9 send to a process?", options: ["SIGTERM", "SIGHUP", "SIGKILL", "SIGINT"], answer: 2, explain: "Signal 9 is SIGKILL. It cannot be caught or ignored and immediately terminates the process." },
  { question: "What does the shebang line #!/bin/bash at the top of a script do?", options: ["A comment explaining the script", "Tells the OS which interpreter to use", "Enables bash strict mode", "Required syntax for all scripts"], answer: 1, explain: "The shebang (#!) followed by interpreter path tells the OS what program should run this script." },
];

export const quickTerminalCommands = [
  "help",
  "ls",
  "pwd",
  "whoami",
  "date",
  "uname -a",
  "echo hello",
  "cat /etc/os-release",
  "ps aux",
  "df -h",
  "free -h",
  "uptime",
];

export function simulateCommand(rawCommand) {
  const command = rawCommand.toLowerCase().trim();
  const outputs = {
    help: ["Available commands (simulated): ls, pwd, whoami, date, uname -a, echo, cat /etc/os-release,", "ps aux, df -h, free -h, uptime, history, env, hostname, id, clear", "", "This is a simulator - it shows realistic outputs for common Linux commands."],
    ls: ["bin  boot  dev  etc  home  lib  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var"],
    "ls -la": ["total 80", "drwxr-xr-x  2 user user 4096 Mar 16 09:00 .", "drwxr-xr-x 18 root root 4096 Mar 10 12:00 ..", "drwxr-xr-x  8 user user 4096 Mar 16 08:45 documents", "-rw-r--r--  1 user user  220 Mar  1 00:00 .bash_profile", "-rw-r--r--  1 user user 3526 Mar  1 00:00 .bashrc", "drwxr-xr-x  3 user user 4096 Mar 14 10:30 projects", "-rw-------  1 user user  845 Mar 15 23:59 .ssh"],
    pwd: ["/home/user"],
    whoami: ["user"],
    date: [new Date().toString()],
    "uname -a": ["Linux linuxpro-machine 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux"],
    "cat /etc/os-release": ['NAME="Ubuntu"', 'VERSION="22.04.3 LTS (Jammy Jellyfish)"', "ID=ubuntu", "ID_LIKE=debian", 'PRETTY_NAME="Ubuntu 22.04.3 LTS"', 'VERSION_ID="22.04"', 'HOME_URL="https://www.ubuntu.com/"'],
    "ps aux": ["USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND", "root         1  0.0  0.1 168408 13024 ?        Ss   09:00   0:01 /sbin/init", "root       234  0.0  0.0  72248  1960 ?        Ss   09:00   0:00 /usr/sbin/sshd", "user      1024  0.2  0.3 412348 28460 pts/0   Sl   09:05   0:02 /usr/bin/bash", "user      1337  0.0  0.1 164240 12432 pts/0   S    09:10   0:00 vim notes.txt", "user      2048  0.5  0.8 998432 65312 pts/1   Sl   09:20   0:05 node server.js"],
    "df -h": ["Filesystem      Size  Used Avail Use% Mounted on", "udev            3.8G     0  3.8G   0% /dev", "tmpfs           785M  1.4M  784M   1% /run", "/dev/sda1        50G   18G   30G  37% /", "tmpfs           3.9G  104M  3.8G   3% /dev/shm", "/dev/sda2       200G   98G   92G  52% /home"],
    "free -h": ["              total        used        free      shared  buff/cache   available", "Mem:           7.7Gi       3.1Gi       2.9Gi       287Mi       1.7Gi       4.1Gi", "Swap:          2.0Gi          0B       2.0Gi"],
    uptime: [" 09:42:15 up 2 days, 14:23,  2 users,  load average: 0.42, 0.38, 0.35"],
    history: ["1  ls -la", "2  cd projects", "3  git status", "4  vim app.py", "5  python3 test.py", '6  grep -r "error" logs/', "7  tail -f /var/log/syslog"],
    env: ["HOME=/home/user", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "SHELL=/bin/bash", "USER=user", "LANG=en_US.UTF-8", "TERM=xterm-256color"],
    hostname: ["linuxpro-machine"],
    id: ["uid=1000(user) gid=1000(user) groups=1000(user),4(adm),24(cdrom),27(sudo),30(dip)"],
    clear: [],
  };

  if (command === "clear") {
    return { clear: true, lines: [] };
  }

  if (outputs[command]) {
    return { clear: false, lines: outputs[command] };
  }

  if (command.startsWith("echo ")) {
    return { clear: false, lines: [rawCommand.substring(5)] };
  }

  if (command.startsWith("ls")) {
    return { clear: false, lines: ["bin  conf  data  logs  public  scripts  tmp"] };
  }

  if (command.startsWith("cd ")) {
    return { clear: false, lines: [`Changed directory to ${rawCommand.substring(3)}`] };
  }

  if (command.startsWith("man ")) {
    return { clear: false, lines: [`Displaying manual for: ${rawCommand.substring(4)}`, "(Tip: In a real terminal, press q to exit man pages)"] };
  }

  if (command.startsWith("cat ")) {
    return { clear: false, lines: [`cat: ${rawCommand.substring(4)}: File contents would appear here in a real terminal`] };
  }

  if (command.startsWith("grep ")) {
    return { clear: false, lines: ["(grep simulation) Searching for pattern in specified files...", "Tip: Try grep in a real terminal for actual results!"] };
  }

  return { clear: false, lines: [`bash: ${rawCommand}: command not found (or not simulated)`, "Type 'help' to see available simulated commands"] };
}
